export const APP_FETCH_POST_LIST_REQUEST = 'APP_FETCH_POST_LIST_REQUEST';
export const APP_FETCH_POST_LIST_SUCCESS = 'APP_FETCH_POST_LIST_SUCCESS';
export const APP_FETCH_POST_LIST_ERROR = 'APP_FETCH_POST_LIST_ERROR';

export const APP_LOGIN_REQUEST = 'APP_LOGIN_REQUEST';
export const APP_LOGIN_SUCCESS = 'APP_LOGIN_SUCCESS';
export const APP_LOGIN_ERROR = 'APP_LOGIN_ERROR';

export const APP_TOAST_CREATE = 'APP_TOAST_CREATE';
export const APP_TOAST_DELETE = 'APP_TOAST_DELETE';